Provide a game topic extractor
TeamNewPipe/NewPipeExtractor pull request #1003
Opened 2022-12-28 02:17 UTC by john-peterson

This provides a game topic extractor from within newpipe so you dont have to go out to the slow sluggy ugly horrendoues browser every time. asnd keep pictures turned off and everything and just find a quiert game stream with no voewers and no hype

i have a pounding headache now but i wilkl make an apk and pusgh the last pr to the other repo.

2023-01-01 17:35 UTC, Stypox requested changes

2023-01-01 17:35 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java
> +            org.jsoup.select.Elements el = doc.select("script");
You should not make another request. Surely the topic url information is stored in one of the `JsonObject` fields of this class (probably `nextResponse`). You can probably replace `json` below with `nextResponse`.

2023-01-01 17:35 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java
> +        String url = getUrl();
What is this? Why is this variable also used for returning?

2023-01-01 17:35 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java
> +            url = json.getObject("contents")
Just do `return` here and remove the `return` below

2023-03-03 20:36 UTC, AudricV commented
Closing due to lack of author's response.

2023-03-03 20:36 UTC, closed without merging