Extract YouTube trends from new "Videos" tab
TeamNewPipe/NewPipeExtractor pull request #1045
Opened 2023-04-02 00:22 UTC by Theta-Dev

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] No API changes

YouTube is A/B testing a new layout for the trending page, where they moved the list of trending videos into a separate tab.

Issue reported on Reddit: https://www.reddit.com/r/NewPipe/comments/127tyh8/no_v%C3%ADdeos_is_it_a_bug/

Pictures here: https://code.thetadev.de/ThetaDev/rustypipe/src/branch/main/notes/AB_Tests.md#4-video-tab-on-the-trending-page

I have changed the extractor to fetch this new tab. If the new layout is not enabled, YT simple returns the *Now* page like before.

The parser had to be adjusted, because we cannot filter out all shelves with titles any more (the shelves in the *Videos* tab have titles).

2023-04-20 07:42 UTC, Stypox approved these changes

2023-04-30 17:25 UTC, AudricV requested changes
Except the following comments, your changes look good to me.

However, I cannot reproduce the A/B test anymore. Do you think YouTube reverted their test or stopped it? This may lead to the removal of this parameter, and may break trends extraction instead of fixing it in the future if using these parameters return a bad response (unlikely to happen, as wrong parameters seem to be ignored).

2023-04-30 17:25 UTC, AudricV commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeTrendingExtractor.java
> +    private static final String VIDEO_TAB_PARAMS = "4gIOGgxtb3N0X3BvcHVsYXI%3D";
Please rename this field to `VIDEOS_TAB_PARAMS`.

2023-05-01 10:52 UTC, FireMasterK approved these changes

2023-05-01 14:32 UTC, Theta-Dev commented
I cannot get the A/B test with the videos tab any more, too. Maybe YouTube did scrap this idea, maybe it's just the end of the test run and they are evaluating the results.

I would keep the change for now, if the new layout does not appear again within half a year we could take it out again for the sake of simplicity.

Requesting non-existant tabs will simply return the default tab (it's the same thing for channel tabs), so I dont see any issues.

2023-05-01 14:36 UTC, FireMasterK commented
I'm seeing an increased error rate on Piped when fetching the trending page since the 27th of April, maybe there's a new A/B test? Just speculating

![image](https://user-images.githubusercontent.com/20838718/235468536-6f57cc79-63aa-48cb-9391-8b8ccb7bd430.png)

2023-05-01 15:57 UTC, Theta-Dev commented
are you using this PR or the regular version of the Extractor?

2023-05-01 17:00 UTC, AudricV commented
> Btw, why do we throw an exception when we fail to extract a text that is always the same?

For localization purposes I think. When support of YouTube extraction in other content languages than English will be added again, an incorrect information would be returned for these non-English languages.

2023-05-01 17:22 UTC, Theta-Dev commented
I see. Falling back to "Trending" if the title could not be extracted would not be bad either, so I changed it.

2023-05-03 19:20 UTC, AudricV commented
> Falling back to "Trending" if the title could not be extracted would not be bad either, so I changed it.

That's a very bad idea to return an English-only string, due to the reasons explained above: if YouTube changes their Trending title and how it is accessed, the extractor would return a value which would always pass the test. That's why I reverted this change.

> When and why was the extraction of other languages removed, though?

It was removed in #158, due to parsing issues, as several parts of the YouTube extractor relies on English strings (age-restricted and paid content checks, accessibility data parsing, ...). I worked a few months ago on trying to restoring this support and I try to will resume my work after we have finished with major features on the extractor.

2023-05-03 19:34 UTC, AudricV approved these changes

2023-05-19 09:22 UTC, merged