[YouTube] Make some improvements and fixes
TeamNewPipe/NewPipeExtractor pull request #1127
Opened 2023-11-19 00:25 UTC by AudricV

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).

This PR does multiple improvements and fixes to the YouTube service in the extractor.

- It updates InnerTube clients' version and devices' OS version and model;
- It improves payloads and URLs of InnerTube requests:
  - for every InnerTube request, a `request` object is set with the following properties:
    - `internalExperimentFlags` set to an empty array;
    - `useSsl` set to `true`;
    - `lockedSafetyMode` set to `false`.
  - for YouTube Music:
    - remove `alt` query parameter, as it is not used anymore by the website;
    - add `prettyPrint` query parameter with `false` value on YouTube Music search continuations.
- It adds `utcOffsetMinutes` to all InnerTube payloads, previously only set on YouTube Music search continuations, which should make returned dates consistent between timezones and countries on which the extractor is ran;
- It adds missing `prettyPrint` query parameter to some test `InnerTube` requests;
- It switches to YouTube's new consent cookie;
- It makes only extracting search results corresponding to a search type, as YouTube returns sometimes videos inside channel search results for example;
- It supports new A/B tested like data (like in #1123, these changes have been written before #1123 was opened) and avoid like count conversion from integer to long;
- It removes `Channels` channel tab support, as this tab has been removed by YouTube;
- It fixes all broken tests and updates mocks.

For more details, please look at commit messages and code changes.

NewPipe debug test APK: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/13401782/app-debug.zip)

2023-11-30 21:26 UTC, AudricV commented
> This is still EU-only, right?

I don't think so, but I am not sure.

> In addition to the question above, will the users see any noticeable change with this, or is this all under-the-hood stuff?

Some changes will be seen by users, as #1133 is fixed by this PR.

2023-12-07 14:53 UTC, Stypox requested changes
Thank you! I reviewed the commits one by one and noticed only one suspect change.

I tested on an emulator and everything worked fine: [app-debug.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/13601620/app-debug.zip)

As per the crisis resources change, shouldn't the extractor still return the warning as a meta info? E.g. see screenshot below. I will open a PR independent from this one if it's ok for you.

![image](https://github.com/TeamNewPipe/NewPipeExtractor/assets/36421898/1fa6cff3-089e-4fad-810d-72be1a02b6c3)

2023-12-07 19:01 UTC, AudricV commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java
>                  .value("fetchLiveState", true)
Yes, because it was at the wrong place and now it is at the good place.

2023-12-07 20:17 UTC, Stypox approved these changes
Feel free to merge once you update the client versions!

2023-12-09 13:07 UTC, merged