Use TreeMap in Response
TeamNewPipe/NewPipeExtractor pull request #1198
Opened 2024-07-20 07:50 UTC by Isira-Seneviratne

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
----
Store the response headers in a [`TreeMap`](https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html). This allows the header value retrieval to be optimised as `TreeMap` orders its keys using a comparator.

2024-07-20 11:26 UTC, Isira-Seneviratne commented
I've revised the code a bit, to reuse the map if it is already a SortedMap.

2025-03-19 02:32 UTC, Isira-Seneviratne commented
> A related test is failing, something is wrong with the changes
> 
> ```
> Invalid response type (got "null", excepted a JSON response) (response code 200)
> org.schabi.newpipe.extractor.exceptions.ExtractionException: Invalid response type (got "null", excepted a JSON response) (response code 200)
> 	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:71)
> 	at org.schabi.newpipe.extractor.services.youtube.YoutubeSuggestionExtractorTest.testIfSuggestions(YoutubeSuggestionExtractorTest.java:55)
> ```

I wasn't able to reproduce the issue locally, the header value is being returned as expected.

2025-03-21 10:48 UTC, Stypox requested changes
Somewhere we have to iterate through all headers anyway: either in the `Response` constructor, or in the `getHeader()` function, since we don't know with which `Map` the `Response` is being built (it might be a `SortedMap` sorted according to a wrong criterion). So I would suggest recreating a new `TreeMap` every time in the `Response` constructor, since that's called only once, while `getHeader` might be called multiple times. 

Replying to @TobiGr, I think we can't use a `HashMap` if we want a sorted map. But in any case, given the small amount of headers that there usually are (<20), the `O(log n)` of the `TreeMap` is actually much faster than the `O(1)` of the `HashMap`: hash maps have a big constant in the `O(1)` and get faster only after n grows large enough.

Another option would be to create a hash map where keys are already lowercased in the constructor, and then just accessing the map with `name.lowercase()` in `getHeader()`.

In general I don't think this change is so important anyway, since the `O(n)` we had in `getHeader()` is not so bad given that `n` is small, and `getHeader()` is basically never used anyway:
![image](https://github.com/user-attachments/assets/edeb20fa-5eb1-4c54-9ecf-1fc8d151ec5c)

So I would just keep the old `O(n)` behavior in `getHeader()`, but `O(1)` in the constructor, rather than switching to `O(n)` in the constructor (which is executed **all the time**) and `O(log n)`/`O(1)` in `getHeader()` (which is basically never called).

2025-03-21 10:48 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/downloader/Response.java
> +                    @Nonnull final Map<String, List<String>> responseHeaders,
Why is this changed to be `@Nonnull`? Isn't this a breaking change?

2025-03-21 10:48 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/downloader/Response.java
> +        }
Mmmh, this still means that all items are reprocessed when building a `Response` in case the headers were not already in a `SortedMap`. Also, how can you be sure that `responseHeaders` was built using `String.CASE_INSENSITIVE_ORDER`?

I would just build a new `TreeMap` every time.

2025-03-22 09:42 UTC, closed without merging