Fix issue #4213
TeamNewPipe/NewPipeExtractor pull request #394
Opened 2020-09-03 00:31 UTC by kirisakow

trim the last char of the URL if it is a closing parenthesis

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

2020-09-03 06:39 UTC, wb9688 commented
YouTube trims any additional characters from `v`. This implementation is incorrect.

2020-09-03 16:28 UTC, kirisakow commented
Dear @wb9688, perhaps I was not clear enough. What I am trying to fix here is NewPipe's being unable to handle YouTube links which, inadvertedly, include a closing parenthesis at the end. I invite you to open this very page in your favorite web browser for Android, and try to open with NewPipe each one of the two links below: the first shall work, whereas the second shall not. And that's what I am trying to fix here by trimming the last character from the video's ID if that character is a closing parenthesis.

1. [https://www.youtube.com/watch?v=mBuoZY7kAlg](https://www.youtube.com/watch?v=mBuoZY7kAlg)
2. [https://www.youtube.com/watch?v=mBuoZY7kAlg)](https://www.youtube.com/watch?v=mBuoZY7kAlg%29)

Thank you for your attention. Please help me implement that fix.

2020-09-03 16:48 UTC, wb9688 commented
Try opening e.g. https://www.youtube.com/watch?v=mBuoZY7kAlgwhatever. Also note how with e.g. https://www.youtube.com/watch?list=PLEqQd15F3NFGFUYJhz8KvGNz-QDhJVynT&v=OGS7c0-CmRswhatever it will strip the other parameters.

2020-09-03 17:17 UTC, kirisakow commented
Dear friend, please watch me reproducing the issue with my Android device in Firefox for Android web browser:

https://youtu.be/bZP0jtp9WrQ

2020-09-03 18:02 UTC, wb9688 commented
Again, YouTube strips any additional characters (and if there are additional characters, it will strip other parameters), while NewPipe considers the URL simply invalid, however this PR naively strips the last character if it's ), which is also incorrect as it should exactly follow YouTube's behavior.

2020-09-03 19:10 UTC, kirisakow commented
All right, as you wish

2020-09-03 19:14 UTC, opusforlife2 commented
@kirisakow He's talking about implementing the generic Youtube-like behaviour so it handles all cases of improper URLs, not just the parenthesis one. Did you close the PR because you don't wish to take that on?

2020-09-03 22:14 UTC, kirisakow commented
I closed because l wasn't told what needs to be done — only that my solution was incorrect.

If you are open to tell me what you think needs to be done — I'll do it.

2020-09-04 11:40 UTC, Stypox commented
Let me try to provide a clearer explanation, sorry for the confusion ;-) 
Your implementation is not optimal since:
- it is applied to all services, but some services could have a closing parenthesis as  part of the id, so in that case the link would be made invalid. Therefore it should only be applied to YouTube (see YoutubeStreamLinkHandlerFactory, YoutubePlaylistLinkHandlerFactory and the similar ones)
- it does not behave the same way as the official youtube client. What wb9688 suggested was to not only remove parenthesis, but also all spare characters at the end of the url, while you are at it. That's what the official yt app and official browser version do: every character after the id is just ignored. To make this compliant you could trim the id to only the first N characters (where N is the length of the id, =11 for yt videos)

Thank you for your contribution and sorry for the confusion ;-)

2020-09-04 11:49 UTC, Stypox commented
Oh, forgot to add that you should keep this in mind while implementing: when the official browser version gets a video [didn't check other features] url with an id parameter `v=` longer than 11 chars, all of the following url parameters are ignored

2020-09-05 02:22 UTC, kirisakow commented
Another solution applied to `YoutubeStreamLinkHandlerFactory` class alone (for now). Before I move on, please tell me if you guys are happy with it.

2020-09-05 21:45 UTC, kirisakow commented
I applied the suggested solution to the `YoutubeStreamLinkHandlerFactory` class alone (for now). Before I move on, please tell me if you guys are happy with it. @Stypox @wb9688 @opusforlife2 @gzsombor

2020-09-06 10:22 UTC, opusforlife2 commented
I'm not a dev so I can't comment on that aspect, but thank you for continuing to work on this. 🥂

2020-09-06 13:45 UTC, Stypox requested changes
This looks better, thank you ;-)
I only pointed out a few style issues, but the overall approach is good. Add `final` to all variables as you can, including function arguments.

2020-09-06 13:45 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
> +            return m.find() ? m.group(1) : "";
Return `null` instead of an empty string, if you found nothing (also remember to add `@Nullable` to the function)

2020-09-06 13:45 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
>      private static boolean isId(@Nullable String id) {
We might consider removing `isId()` altogether and replacing
```java
if (isId()) {
    return extractId()
}
```
with 
```java
final String extractedId = extractId(id);
if (extractedId != null) {
    return extractedId;
}
```
which does one regex comparison less, and is even clearer imo

2020-09-06 13:45 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
> +            Matcher m = Pattern.compile("([a-zA-Z0-9_-]{11})").matcher(id);
Move `Pattern.compile("([a-zA-Z0-9_-]{11})")` to a `public static final` class field, to prevent compiling it every time.

2020-09-08 01:30 UTC, kirisakow commented
@Stypox Done

2020-09-08 17:55 UTC, Stypox requested changes
Please add one or two tests for urls with this longer-than-usual id (in YoutubeStreamLinkHandlerFactoryTest should do)
Thank you!

2020-09-08 17:55 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
> +                    final String extractedId = extractId(possiblyId);
Merge this and the above line into
```java
final String possiblyId = extractId(schemeSpecificPart.substring(2));
```

2020-10-23 08:13 UTC, TobiGr reviewed
Thanks

2020-10-23 08:13 UTC, TobiGr commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
> +            Matcher m = YOUTUBE_VIDEO_ID_REGEX_PATTERN.matcher(id);
```suggestion
            final Matcher m = YOUTUBE_VIDEO_ID_REGEX_PATTERN.matcher(id);
```

2020-10-23 14:17 UTC, TobiGr approved these changes

2020-10-23 14:19 UTC, wb9688 requested changes
Issues I pointed out still aren't fixed…

2020-10-25 13:28 UTC, Stypox commented
Even though you this does not handle urls exactly like youtube, like `@wb9688` said, I prefer this behaviour. The reason that urls sometimes have additional characters at the end is not something done by youtube, but is something done by accident when writing e.g. messages. So if NewPipe can understand that a `&list=` url comes from a playlist instead of falling back to only using `&v=` like YouTube does it's only a plus. Therefore I'm merging this.

2020-10-25 13:37 UTC, Stypox approved these changes
I rebased on dev and run the tests again, everything works fine. Thank you!
~~@ TobiGr I can't merge due to other failing tests, could you do that?~~ nevermind, I can

2020-10-25 13:39 UTC, merged