Add uploader verified by service extraction
TeamNewPipe/NewPipeExtractor pull request #521
Opened 2021-01-22 18:04 UTC by B0pol

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

2021-01-22 19:04 UTC, TobiGr requested changes
Please implement the expectedVerified methods in the default*Tests. 
Btw. I assigned that issue to me, so most of that is implemented. You can have a look here: https://github.com/TobiGr/NewPipeExtractor/commit/b772d5dbfb0a6c120cebcbb4d54f5ada9191f594 ...

2021-01-22 20:12 UTC, B0pol commented
Sorry, I did not notice that.
I think we should keep this PR, there is SoundCloud implementation, artist verified badge, extracted in comments and channel…
I will push the defaultTests soon and let you implement the NewPipe part then.

2021-01-22 20:19 UTC, TobiGr commented
Yes, we should use your implementation. I did not have time to finish everything yet (notice the incomplete JDoc, some missing tests, etc.).
As I said, I won't have much time for NewPipe in the next weeks. You can use the changes from my commit and apply them to your PR.

2021-01-22 22:20 UTC, B0pol commented
> Please implement the expectedVerified methods in the default*Tests.

Done.

2021-01-31 11:36 UTC, TobiGr approved these changes

2021-02-18 15:39 UTC, merged

2021-02-18 17:00 UTC, XiangRongLin commented on extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/search/YoutubeSearchExtractorTest.java
> +            NewPipe.init(DownloaderTestImpl.getInstance());
@B0pol Can do another PR where you replace this with the `DownloaderFactory`