support /watch/ and /v/ folders
TeamNewPipe/NewPipeExtractor pull request #536
Opened 2021-02-10 16:08 UTC by B0pol

fixes #543

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

I trust the tests

2021-02-13 12:22 UTC, TobiGr reviewed
looks good. two small things.

2021-02-13 12:22 UTC, TobiGr commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
> +                String id = path.split("/")[1];
`substring` is way faster than `split`, so please use that method instead.

2021-02-13 21:10 UTC, B0pol commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
> +    private static final List<String> folders = Arrays.asList("embed/", "shorts/", "watch/", "v/", "w/");
path containing what? folders

2021-02-16 16:13 UTC, Stypox requested changes
LGTM

2021-02-16 16:13 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java
> +    private static final List<String> subpaths = Arrays.asList("embed/", "shorts/", "watch/", "v/", "w/");
```suggestion
    private static final List<String> SUBPATHS = Arrays.asList("embed/", "shorts/", "watch/", "v/", "w/");
```

2021-02-16 19:07 UTC, Stypox approved these changes

2021-02-16 19:23 UTC, merged