Fix YouTube channels contination
TeamNewPipe/NewPipeExtractor pull request #570
Opened 2021-03-04 19:21 UTC by TiA4f8R

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).

Fix YouTube channels continuation extraction by using the same method as @XiangRongLin in #567.

APK to test: https://github.com/TiA4f8R/NewPipe/suites/2178388837/artifacts/44814609

(Sorry for the commits, I can't use my computer right now.)

2021-03-04 19:25 UTC, pooppp3 approved these changes
hi

2021-03-04 21:02 UTC, FireMasterK approved these changes

2021-03-04 21:38 UTC, B0pol requested changes

2021-03-04 21:38 UTC, B0pol commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelExtractor.java
>          final String clickTrackingParams = continuationEndpoint.getString("clickTrackingParams");
```suggestion
```
it should be removed if not used

2021-03-05 08:13 UTC, XiangRongLin commented
The mocks for the other tests also need to be regenerated

2021-03-05 12:14 UTC, TobiGr commented
@XiangRongLin Can you check, whether I've done this right?

2021-03-05 13:07 UTC, B0pol approved these changes

2021-03-05 14:18 UTC, XiangRongLin commented
> @XiangRongLin Can you check, whether I've done this correctly?

From a glance it looks good.

Basically if the tests pass with the mock downloader then its good.

2021-03-05 14:26 UTC, merged