[YouTube] Fix getting stream type of live streams
TeamNewPipe/NewPipeExtractor pull request #651
Opened 2021-06-08 21:10 UTC by TobiGr

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Live streams are sometimes not recognized as such. That is causing the duration extraction to fail.

Fixes https://github.com/TeamNewPipe/NewPipeExtractor/runs/2769405487?check_suite_focus=true#step:5:169

2021-06-09 13:40 UTC, Stypox requested changes
Code looks good; I trust you that this works ;-)

2021-06-09 13:40 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java
> +        for (final Object object: thumbnailOverlays) {
```suggestion
        for (final Object object : thumbnailOverlays) {
```

2021-06-10 14:51 UTC, TobiGr commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java
> +        for (final Object object: thumbnailOverlays) {
Done

2021-06-10 17:26 UTC, Stypox approved these changes

2021-06-12 15:57 UTC, merged

2021-06-13 17:20 UTC, litetex commented
@TobiGr 
Code seems to be faulty: 
Now every video is shown as "LIVE":
![grafik](https://user-images.githubusercontent.com/40789489/121816414-c4384d80-cc7b-11eb-8aa0-4f61fcc0a821.png)

Please check:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/0cb48e36bd8ff798090fc2f174f2430959b46a88/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java#L76
Looks like the "or" ``||`` should be an "and" ``&&``

2021-06-13 19:26 UTC, TobiGr commented
Uhm. No. That should not be the case. Let me take a look. Thank you for the heads up!