Add support for extracting comment replies continuation
TeamNewPipe/NewPipeExtractor pull request #703
Opened 2021-08-04 12:29 UTC by FireMasterK

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

This takes an alternative approach to #576

@Stypox could you verify that this approach is okay?

2021-08-04 15:59 UTC, Stypox commented
Does it work also with comments continuations? Would this approach allow having both nested replies (for Peertube, I think) and replies continuations (when not all replies are loaded at once)?

2021-08-04 16:29 UTC, FireMasterK commented
> Does it work also with comments continuations

Yes! Nothing should break it, although I will check it manually. I would have to check this once again as I have not check if there's a different JSON structure for these continuations.

> Would this approach allow having both nested replies

Yes, each comment would have an option replies `Page`. In YouTube there's only one level, so it would be null there.

To get reply Comments, you just call `getMoreItems` with the replies `Page`.


> replies continuations

This would be a regular continuation / getNextPage(), nothing should change.

2021-08-04 16:39 UTC, Stypox commented
@FireMasterK ok, then this approach is good. Thank you :-)

2021-08-04 16:48 UTC, FireMasterK commented
Just one small issue - this implementation doesn't support multi-level threads in one page request, but I think that can be done later. (I'm not sure if any services do this either)

2021-09-07 06:50 UTC, Mhowser commented
Is this PR ready to be reviewed and merged soon?

2021-09-10 14:27 UTC, Stypox requested changes

2021-09-10 14:27 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/comments/CommentsInfoItemExtractor.java
> +     * @return the continuation Page for the replies
```suggestion
     * @return the continuation Page for the replies, or null if replies are not supported
```

2021-09-10 14:27 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java
> +        String jsonKey = contents.getObject(0).has("commentThreadRenderer") ? "commentThreadRenderer" : "commentRenderer";
```suggestion
        final String jsonKey = contents.getObject(0).has("commentThreadRenderer") ? "commentThreadRenderer" : "commentRenderer";
```

2021-09-10 14:27 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java
> +                    jsonKey);
Put this on one line

2021-09-10 14:27 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsInfoItemExtractor.java
> +    private JsonObject getCommentRenderer() throws ParsingException {
Why is there `throws ParsingException`?

2021-09-10 14:27 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsInfoItemExtractor.java
> +            return null;
I guess if `YoutubeCommentsInfoItemExtractor` is used as a reply extractor this `return null` would kick in for YouTube, wouldn't it? Add a comment to explain this.

2021-09-11 19:37 UTC, FireMasterK commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsInfoItemExtractor.java
> +    private JsonObject getCommentRenderer() throws ParsingException {
`JsonUtils` throws it, that's why.

2021-09-13 06:48 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsInfoItemExtractor.java
> +    private JsonObject getCommentRenderer() throws ParsingException {
Okk

2021-09-13 06:59 UTC, Stypox approved these changes
Perfect, thank you :-D

2021-09-13 07:03 UTC, Stypox commented
This will be merged after release 0.20.10 is released

2021-09-13 14:46 UTC, TobiGr commented
Do we need to squash the commits?

2021-09-14 16:59 UTC, Stypox commented
I don't think that's needed

2021-09-14 21:58 UTC, merged