Extract Uploader's Avatar on YouTube.
TeamNewPipe/NewPipeExtractor pull request #723
Opened 2021-09-01 18:42 UTC by FireMasterK

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

2021-09-01 18:49 UTC, Stypox commented
Thank you @FireMasterK! Could you add some description? Does this add support for channel avatars of stream info items?

2021-09-01 18:51 UTC, FireMasterK commented
> Thank you @FireMasterK! Could you add some description? Does this add support for channel avatars of stream info items?

Done! It indeed does, this currently works in the Search and Trending pages I believe as YouTube doesn't provide these anywhere else.

2021-09-01 18:58 UTC, Stypox requested changes
Looks almost good to me :-)

2021-09-01 18:58 UTC, Stypox commented on extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/search/YoutubeSearchExtractorTest.java
> +                assertNotNull(((StreamInfoItem) item).getUploaderAvatarUrl());
This query could technically also return channel info items and the test would fail, wouldn't it? I'd add an `if (item instanceof StreamInfoItem)`

2021-09-01 18:58 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamInfoItem.java
> +    public void setUploaderAvatarUrl(String uploaderAvatarUrl) {
```suggestion
    public void setUploaderAvatarUrl(final String uploaderAvatarUrl) {
```

2021-09-01 18:58 UTC, Stypox commented on extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/search/YoutubeSearchExtractorTest.java
> +            for (InfoItem item : items) {
```suggestion
            for (final InfoItem item : items) {
```

2021-09-01 18:58 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java
> +            return JsonUtils.getArray(videoInfo, "channelThumbnailSupportedRenderers.channelThumbnailWithLinkRenderer.thumbnail.thumbnails").getObject(0).getString("url");
Better to break it into two
```suggestion
            return JsonUtils.getArray(videoInfo, "channelThumbnailSupportedRenderers.channelThumbnailWithLinkRenderer.thumbnail.thumbnails")
                .getObject(0).getString("url");
```

2021-09-01 19:11 UTC, Stypox commented on extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/search/YoutubeSearchExtractorTest.java
> +                assertNotNull(((StreamInfoItem) item).getUploaderAvatarUrl());
Oh, didn't see that one, good

2021-09-01 19:12 UTC, Stypox approved these changes

2021-09-01 20:59 UTC, TobiGr requested changes
I think this can also be tested roughly in `DefaultTests.defaultTestListOfItems()`.

Please remove  `throws ParsingException` when overriding the method and returning `null`

2021-09-01 20:59 UTC, TobiGr commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/peertube/extractors/PeertubeStreamInfoItemExtractor.java
> +        return null;
```suggestion
        final JsonObject account = item.getObject("account");
        if (account.has("avatar") && !account.isNull("avatar")) {
            return baseUrl + account.getObject("avatar").getString("path");
        }
        return null;
```

2021-09-02 10:48 UTC, FireMasterK commented
> I think this can also be tested roughly in DefaultTests.defaultTestListOfItems().

What about services which in which it's not extracted in? Another thing to note is that even on YouTube, it's not provided everywhere.

2021-09-03 13:57 UTC, TobiGr commented
Testing this should be similar to testing the thumbnail URL
```Java
            final String uploaderAvatarUrl = item.getUploaderAvatarUrl();
            if (!isNullOrEmpty(uploaderAvatarUrl)) {
                assertIsSecureUrl(uploaderAvatarUrl);
            }
```

2021-09-03 15:36 UTC, FireMasterK commented
> Testing this should be similar to testing the thumbnail URL
> 
> ```java
>             final String uploaderAvatarUrl = item.getUploaderAvatarUrl();
>             if (!isNullOrEmpty(uploaderAvatarUrl)) {
>                 assertIsSecureUrl(uploaderAvatarUrl);
>             }
> ```

Added, thanks for the clarification on what you meant!

2021-09-03 16:13 UTC, merged