Changes for "Show Replies"
TeamNewPipe/NewPipeExtractor pull request #739
Opened 2021-10-13 23:31 UTC by golfinq

A small change needed for the associated pull request in NewPipe (https://github.com/TeamNewPipe/NewPipe/pull/7244), which stores whether or not the replies have been cached to prevent re-downloading

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

2021-10-15 17:26 UTC, litetex commented
> @Redirion I tried it, and I ran into the `NetworkOnMainThreadException` and I am not familiar with android threads

https://stackoverflow.com/questions/6343166/how-can-i-fix-android-os-networkonmainthreadexception

Btw: I'm pretty sure that this PR will cause problems regarding the comment loading performance and resources required for holding the replies in memory.

2021-10-17 01:13 UTC, golfinq commented
@TobiGr Oh my god, that is what I was missing. I'll see if I can incorporate RXJava to not have to cache the replies to comments. I am doing some reading to learn about it here: https://github.com/ReactiveX/RxJava/tree/3.x/docs

2021-10-20 10:10 UTC, golfinq commented
> 
> 
> I don't understand why you want to do it this way.
> 
> How I imagined it to be used was:
> 
> ```
> CommentsInfo info = CommentsInfo.getInfo(...);
> 
> // Only called when the user clicks on show more
> CommentsInfo replies = info.getReplies() != null ? CommentsInfo.getMoreItems(info, info.getReplies()) : null;
> ```

This was quite helpful in getting off the ground, thanks!

2021-11-13 20:14 UTC, Stypox requested changes

2021-11-13 20:14 UTC, Stypox commented on extractor/src/main/java/org/schabi/newpipe/extractor/comments/CommentsInfoItem.java
> +    public boolean getRepliesOpen() {return this.repliesOpen; }
This should not be done in the Extractor code, since this is just a UI thing

2022-05-08 11:32 UTC, opusforlife2 commented
Closing this for the same reason as #7244.

2022-05-08 11:32 UTC, closed without merging