Add JS lexer to throttling decrypter
TeamNewPipe/NewPipeExtractor pull request #905
Opened 2022-08-20 12:58 UTC by Theta-Dev

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- no API changes

fixes #902

I added a proper javascript lexer to extract the nsig function, because the old naive implementation broke because of regexes containing curly braces.

I copied the tokenizer from Rhino because it is private and removed unneeded function. On top of that I had to add logic to determine whether a slash constitutes a regex delimiter or a division operator. I have adapted that from the [RESS](https://github.com/rusty-ecma/RESS/blob/master/src/lib.rs) library.

I also found an issue with the Rhino JS interpreter. Version 1.7.14 uses javax.lang.model.SourceVersion, which is not available on android. This causes the app to load indefinitely when opening a video. If you have any idea how to fix this without downgrading, please help me. I have no idea why this error did not occur before.
Checked with the debugger, the error occurs when executing the (correctly extracted) javascript.
Perhaps the new deobfuscation function uses a feature of the interpreter which causes it to load the class with the failing import.
https://github.com/mozilla/rhino/issues/1149

For now I downgraded Rhino to v1.7.13.

2022-08-30 17:09 UTC, AudricV requested changes
Thank you for taking care of this fix! Could you please rebase your PR (and so drop the Rhino version downgrade change that you made yourself)?

2022-08-30 17:09 UTC, AudricV commented on extractor/src/test/java/org/schabi/newpipe/extractor/utils/JavaScriptExtractorTest.java
> +    public void testJsExtractor() throws ParsingException {
Remove this unneeded `public` modifier. See [this Sonar rule](https://rules.sonarsource.com/java/RSPEC-5786) for more details.

2022-08-30 17:09 UTC, AudricV commented on extractor/src/test/java/org/schabi/newpipe/extractor/utils/JavaScriptExtractorTest.java
> +    public void testEverythingJs() throws ParsingException, IOException {
Same as above.

2022-09-08 15:03 UTC, Theta-Dev commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeThrottlingDecrypter.java
> -        }
I'll keep the regex one. As simple as it is, it seems to be stable.

2022-09-08 15:39 UTC, AudricV approved these changes
Thank you again for all the efforts you put to fix this issue!

Your changes look good now to me.

2022-09-11 12:13 UTC, Stypox approved these changes
I think this approach looks good, and if we find any better way to do this in the future we can still undo this pretty easily. Code also looks good (I obviously didn't review the copied-over code). Thank you @Theta-Dev!

2022-09-24 17:55 UTC, merged