Add ability to identify short-form `StreamInfoItem`s
TeamNewPipe/NewPipeExtractor pull request #946
Opened 2022-10-17 20:56 UTC by chowder

Addresses https://github.com/TeamNewPipe/NewPipeExtractor/issues/942 

- [V] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [V] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [V] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

2022-10-18 20:54 UTC, TobiGr commented
thank you. I think providing the same information for `StreamInfo` would be nice. Can you do this as well?

2022-10-18 21:02 UTC, chowder commented
I'll have a look to see if I can do the same for `StreamInfo`

Also, I noticed that a number of tests are failing in the CI action, but these failures are unrelated to my changes (the test that I introduced is passing), do I have to fix them?

2022-10-18 21:10 UTC, TobiGr commented
You don't need to fix the unrelated tests, I created a PR to fix them.
However, [this test](https://github.com/TeamNewPipe/NewPipeExtractor/actions/runs/3276083975/jobs/5393324731#step:5:246) should be fixed by you.

2022-10-18 22:27 UTC, chowder commented
Ah thanks, I've regenerated the test mocks now. 

I've also added the same `isShortFormContent` methods for `StreamInfo` and `StreamExtractor`, but haven't added any actual implementations; for YouTube in particular I couldn't find any fields that distinguish between regular and short videos on the `/watch?v=` links (using [this video](https://www.youtube.com/watch?v=R1Ehb3JA-cM) as reference.

2022-10-28 21:16 UTC, AudricV requested changes
Thank you very much! Here are some changes you need to do in this PR.

Could you also rebase it?

2022-10-28 21:16 UTC, AudricV commented on extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java
> +            throw new ParsingException("Could not determine if short-form content", e);
This seems not understandable as an exception message: I suggest using something like this (given by @opusforlife2 to me):

```suggestion
            throw new ParsingException("Could not determine if this is short-form content", e);
```

2022-10-28 21:16 UTC, AudricV commented on extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamExtractor.java
> +     * YouTube Shorts, or Instagram Reels videos.
```suggestion
     * Whether the stream is a short-form content.
     *
     * <p>
     * Short-form contents are contents in the style of TikTok, YouTube Shorts, or Instagram Reels videos.
     * </p>
```

2022-10-28 21:16 UTC, AudricV commented on extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamInfoItem.java
> +
Remove this extra blank line.

2022-10-28 21:16 UTC, AudricV commented on extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamInfoItemExtractor.java
> +     */
You should use the first description everywhere (with my changes, I think), which give us more details about what is this type of contents.

2022-10-28 21:16 UTC, AudricV commented on extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/search/YoutubeSearchExtractorTest.java
> +            assertTrue(hasShortFormContent);
Remove the unneeded `public` test method modifier here. Also, I recommend using for the test Java 8's `Stream` API instead:

```suggestion
        void testShortFormContent() throws IOException, ExtractionException {
            assertTrue(extractor.getInitialPage()
                    .getItems()
                    .stream()
                    .filter(StreamInfoItem.class::isInstance)
                    .map(StreamInfoItem.class::cast)
                    .anyMatch(StreamInfoItem::isShortFormContent));
```

2022-10-29 23:24 UTC, FireMasterK commented
I've addressed the comments and rebased this PR at https://github.com/FireMasterK/NewPipeExtractor/tree/shorts

2022-10-30 01:37 UTC, chowder commented
Thank you so much @FireMasterK, I've cherry-picked your commit addressing the remaining comments.

2022-10-30 12:39 UTC, FireMasterK approved these changes

2022-11-01 10:46 UTC, chowder commented
> Except that I am not sure if we should use setIsShortFormContent(boolean) instead of setShortFormContent(boolean) for setters

I agree, but I was trying to be consistent with other boolean setters - e.g. [`isUploaderVerified`/`setUploaderVerified`](https://github.com/TeamNewPipe/NewPipeExtractor/blob/b1a899fd47ca5db9bc7cf65ac70a5f20178fb47d/extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamInfo.java#L537) 😅

2022-11-01 10:54 UTC, FireMasterK commented
Intellij's setter generator would generate them as `setShortFormContent(boolean)`, I would keep it the way it is. (and to keep things consistent)

2022-11-01 11:19 UTC, merged