[SoundCloud] Implement getUploaderUrl() and isUploaderVerified() for PlaylistInfoItemExtractor
TeamNewPipe/NewPipeExtractor pull request #995
Opened 2022-12-04 17:52 UTC by TobiGr

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Closes #961

2022-12-06 17:17 UTC, TobiGr commented
I should have added that the other services don't support this. I looked into it, but the info is not provided

2022-12-31 15:10 UTC, AudricV requested changes
Please use the `USER_KEY` constant instead of duplicating its value.

2022-12-31 22:56 UTC, AudricV approved these changes

2023-01-02 14:10 UTC, Stypox approved these changes

2023-01-02 14:10 UTC, merged